# Generated by Django 3.0.7 on 2020-06-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='timeofspawn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
